# coding: iso-8859-1

stop =  ['a','about','above','after','again','against','all','am','an','and','any','are','as','at','be',
         'because','been','before','being','below','between','both','but','by','could','did','do','does','doing',
         'down','during','each','few','for','from','further','had','has','have','having','he','her','here','hers',
         'herself','him','himself','his','how','I','if','in','into','is','it','it’s','its','itself','me','more','most',
         'my','myself','nor','of','on','once','only','or','other','ought','our','ours','ourselves','out','over','own',
         'same','should','so','some','such','than','that','the','their','theirs','them','themselves','then','there','there’s',
         'these','they','this','those','through','to','too','under','until','up','very','was','we','were','what','when',
         'where','which','while','who','whom','why','with','would','you','your','yours','yourself','yourselves','\xa0410-975-0099','\xa0','https://1northwealthservices.com/','usStart','Login','ServiceWe','Chair','\xa0410-975-0099', '\xa0','https://1northwealthservices.com/','usStart','Login ', 'ServiceWe ', 'Chair ',
         '410-975-0099','MoreJames BrennanBlog', 'BrennanBlog' ,'James BrennanBlog','MoreJames BrennanBlog ',
         'Start ','usStart ','Get ', 'Get ', 'Skip ', 'https://3dwealthadvisors.com/  ','LLC â€“ Investment ',' LLC â€“ Investment ',
          'Learn ', 'Download ', 'Learn ','Request', ' ', 'Inc.', 'Inc','3rd Creek - Investments', ' LLC â€“ Investment', 'LLC â€“ Investment',
         '3rd Creek3rd Creek ', '© ', '3rd Creek3rd ' ,' Accounting,','Accounting,','Registered Representative ',
          '3CI ', 'DBS CPA',  '3rd ','Tech Sector ', 'Tech Sector',' Tech Sector ',' Tech Sector', 'HomeBlog ', ' HomeBlog ', ' HomeBlog', 'HomeBlog','Volatile Market', ' Volatile Market', ' Volatile Market ', 'Volatile Market ','the@financial'  ,' the@financial', ' the@financial ', 'the@financial ', 'FINANCIAL@financial' , ' FINANCIAL@financial ',' FINANCIAL@financial', 'FINANCIAL@financial ', 'Certification Exam'  ,' Certification Exam ', 'Certification Exam ' ,' Certification Exam' , 'Find ', ' Find ', ' Find','Find', 'Terms of UseTerms of Use ', 'Terms of UseTerms of Use', ' Terms of UseTerms of Use ' , ' Terms of UseTerms of Use', 'Toggle ', ' Toggle ', 'Toggle', ' Toggle','http://www.1650wealth.com/difference/the-fee-only-difference/ ', 'http://www.1650wealth.com/difference/the-fee-only-difference/', ' http://www.1650wealth.com/difference/the-fee-only-difference/', ' http://www.1650wealth.com/difference/the-fee-only-difference/',  
         'Jane BurnhamJane ','3rd Creek - Contact — 3rd Creek - Investments', 'info@3rdcreek.comWe ', 'Contact ', '', 'Account',
          'Admin Login ', 'FINRA ', 'Why Choose Us', 'clients’ ', ' clients’ ',' clients’ ', 'clients’',' clientsâ€™', 'clientsâ€™',  
         'Fixed Income ', 'Investment ','component&link=8e300a0aceae54db60880073dc561f2e5f36539c','clientsâ€™ ' ,' clientsâ€™ ' 
         'Menu', 'Mobile', 'component&print=1&page=','Friday ', 'GE ', 'Contact ', 'Micron Poised ', 'Complimentary '
         'Download', 'c7e0741a15873c5b66e284bf6774ec6267b55cbf', 'Podcast',' Complimentary ','Download','Accounting',
         'LLC ', 'LIC.#0F30083CA INS', 'LLCInvestment ', 'LIC.#0F30083 ', '12-Squared ',  'Proudly ' ,' â€œde Waal Straatâ€ ',
          'LLC – Investment ', 'LIC.#0F30083 Home ', 'a Registered Investment Adviser', 'Home ','Your Privacy',
         'clients’ ', 'Download Your Copy ', 'Content  Learn ', 'Featured InWelcome ', 'Welcome ', 'â€œde Waal Straatâ€',
         'Featured InOFFICE LOCATION',  'We','Connect ', 'Will ', 'Knowledgeably Applied', 'MeForgot ', 'â€œde Waal Straatâ€ ',
          'Directions ','Approach','Contact Us','SubmitFullName FullName', 'Submit', 'Buffett', 'Select', 
         'SubmitFullName',  'Warren', 'Submit','Menu', ' HOME', 'Menu', ' HOME', ' Menu ', ' Menu', ' HOME',
         ' HOME', ' Menu ', ' Menu','HOME', 'Menu ','Feel ',  'Email Address ',  'Twitter ', 'N. Clybourn Ave',
         'Evanston', 'Clybourn Ave', 'W Fulton', 'Lead Investment ', 'Reach ',' Contact - 1 North Wealth Services',
         ' Contact - 1 North Wealth Services ', 'Contact - 1 North Wealth Services', 'Contact - 1 ','Contact - 1'
          ' Contact - 1 ', 'B.A.', 'B.A. ', ' B.A.', ' Contact - 1 ','Nicaragua', ' Managua', ' â€œde Waal Straatâ€',
           'Somalia', 'Palestine', ' Complimentary ' ,'  Welcome ', ' Featured In', ' Learn ', ' Welcome ', ' Roth ', ' Featured ', ' Featured InWelcome ',
         ' http://www.1650wealth.com/difference/the-fee-only-difference/','Featured In',  'Featured ',' AFFILIATIONS','http://www.naepc.org/  :',  ' Fee'
         'Featured ', ' \xa0“de Waal Straat”', '  ', ' Featured ', 'Process',' Process', ' Process ', 'Process ',
         ' http://www.1650wealth.com/difference/the-fee-only-difference/','“de Waal Straat”', 'Featured ',
         'INDEPENDENT',' INDEPENDENT','INDEPENDENT ',' INDEPENDENT ',' Adjunct Professor ',' Registered Rep',
         ' Bachelor ', ' Adjunct ',' Tom ', 'Tom ',' Award Winner',' Featured ', ' Nashua', 'Tom',
         ' http://www.1650wealth.com/difference/the-fee-only-difference/','Registered Rep', 'Bachelor ', 'Adjunct ',
         'Bloomberg Businessweek', 'AFFILIATIONS', 'Tom ', 'Award Winner', 'Featured ','Download Your Copy ',
         'Featured ', '\xa0', ' Featured ', ' http://www.1650wealth.com/difference/the-fee-only-difference/',
         ' Featured ','Featured ','AFFILIATIONS','Discuss ', 'Featured ','“de Waal Straat”', 'Featured ',
         ' New Amsterdam',' INDEPENDENT','Failure ', 'Certified Financial ', 'a Governance Fellow',
         'Certified Financial Planner ', 'Boards ', 'Nationally ', 'Sean ', 'NEXT BIO',
         'Tax Planning ', 'Schwab ', 'LLP', 'Our StoryThe Value ', 'Convert ', 'Roth Conversions', 'NABCAP Award ', 
         'Roth ConversionsThink Long ', 'Legacy Planning ', 'NABCAP Award', 'Roth Conversions ', 'Tucker ',
         'William S. Richardson School of Law ', 'Our Story - Independent', 'Award ',' Fee', 'Process',' Process', ' Process ', 'Process ',
         ' Our StoryThe Value ',' First', ' Convert ',  ' Roth Conversions',' NABCAP Award ',
         ' Skip ',  ' Roth ConversionsThink Long ', ' https://3dwealthadvisors.com/  ','Bob ',  'ted@advwealth.com            ',  'the Top\xa0', 'Clevenger ',  'Reanna Pechner ', 'Ted’s ', 'Matter Expert ', 'Veronica ShafferOperations ', 'Dorothy HaleyBusiness ',  'Veronica ShafferVeronica Shaffer', 'Business ',  'ted@advwealth.com            Ted ',  'Lindsey HaleyLindsey HaleyBusiness ', 'PLANNER™ ', 'Lindsey HaleyBusiness ', 
         ' Home', ' Legacy Planning ', 'NABCAP Award', ' Roth Conversions ', 'clientsâ€™ ','clientsâ€™',' clientsâ€™ ',' clientsâ€™',
         ' William S. Richardson School of Law ', ' Our Story - Independent', ' Award ', ' Fee','Complimentary ',
        'Adjunct Professor ',' Navigation',' Bio - Deanna Suarez','Thoughtful ','Ending ', 'Building ',
          'Write ', 'Building ', 'Registered Investment Adviser',' Wealth Advisorsâ€', '& ', 'Â\xa0  ','Â\xa0Lindsey HaleyBusiness ','Â\xa0Veronica Shaffer',
         'Starting ', 'Starting ',' Commonwealth',' Waiting','Â\xa0Our ', 'Â\xa0Our Services', 'Â\xa0Our Services', 'Â\xa0Our Services', 'Â\xa0Building ', 'F503.452.7820 ', 'F503.452.7820  ', 'Waiting ', 'Â\xa0Building ','Ã—', ' Â\xa0Our ', ' Â\xa0Our Services', ' Â\xa0Â', ' Â\xa0Our Services', '  ', ' Â\xa0Our Services', ' Ã—', ' Â\xa0Building ', ' F503.452.7820 ', ' Ã—', ' Ã—', ' Ã—', ' F503.452.7820  ', ' \xa0Building ', ' Waiting ', ' Â\xa0', ' Â\xa0',
         ' FINRA/SIPC', ' \xa0', ' Â\xa0', ' Â\xa0Building ','able','about','above','according','accordingly',
         'across','actually','after','afterwards','again','against','all','allow','allows','almost','alone',
         'along','already','also','although','always','am','among','amongst','an','and','another','any','anybody',
         'anyhow','anyone','anything','anyway','anyways','anywhere','apart','appear','appreciate','appropriate','are',
         'around','as','aside','ask','asking','associated','at','available','away','awfully','be','became','because','Kate ',
         'become','becomes','becoming','been','before','beforehand','behind','being','believe','below','beside','besides',
         'best','better','between','beyond','both','brief','but','by','came','can','cannot','cant','cause','causes','certain',
         'certainly','changes','clearly','co','com','come','comes','concerning','consequently','consider','considering',
         'contain','containing','contains','corresponding','could','course','currently','definitely','described','despite',
         'did','didn’t','different','do','does','doing','done','down','downwards','during','each','edu','eg','eight','either',
         'else','elsewhere','enough','entirely','especially','et','etc','even','ever','every','everybody','everyone',
         'everything','everywhere','ex','exactly','example','except','far','few','fifth','first','five','followed',
         'following','follows','for','former','formerly','forth','four','from','further','furthermore','get',
         'gets','getting','given','gives','go','goes','going','gone','got','gotten','greetings','had','happens',
         'hardly','has','have','having','he','hello','help','hence','her','here','hereafter','hereby','herein',
         'hereupon','hers','herself','hi','him','himself','his','hither','hopefully','how','howbeit','however']